# Generated by Django 5.1.1 on 2024-10-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Categoria')),
                ('criado_em', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
    ]
