# Generated by Django 5.1.1 on 2024-10-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dep', '0002_categoria_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
